version: '3.4'

services:
  serilog:
    container_name: serilog
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: 'vscode'
    command: sleep infinity

  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  redis:
    container_name: redis
    image: redis:5
    ports:
      - '6379:6379'
    restart: always

  seq:
    container_name: seq
    image: datalust/seq
    ports:
      - '5341:5341'
